Write Changelog. Refs #614
OnroerendErfgoed/atramhasis pull request #615
Opened 2020-10-06 14:59 UTC by koenedaele

2020-10-07 06:55 UTC, cedrikv requested changes
Maybe add a line about replacing bower with npm as package manager? Not sure if that's considered 'breaking'..

2020-10-07 06:55 UTC, cedrikv commented on CHANGES.rst
> +  for this was incomplete and contained buggy. This has been changed to an
> was incomplete and contained buggy.

best replace with "was incomplete and buggy" or "was incomplete and contained bugs"

2020-10-07 06:55 UTC, cedrikv commented on CHANGES.rst
> +  service is too unstable too often. (#537)
> service is too unstable too often

service is unstable too often

2020-10-07 06:55 UTC, cedrikv commented on CHANGES.rst
> +- Provide a simple, printable version of a thesaurus tree. (#533, 532)
forgot # for 532

2020-10-08 08:02 UTC, koenedaele commented
> Maybe add a line about replacing bower with npm as package manager? Not sure if that's considered 'breaking'..

Added one. Please review.

2020-10-08 08:34 UTC, cedrikv approved these changes

2020-10-08 08:40 UTC, merged