#702 update ldf config
OnroerendErfgoed/atramhasis pull request #703
Opened 2022-06-22 07:52 UTC by roefem

2022-06-23 12:24 UTC, goessebr requested changes
Looks fine, output is like asked. 1 remark about the ini config.

2022-06-23 12:24 UTC, goessebr commented on development.ini
> +atramhasis.rdf2hdt = /usr/local/bin/rdf2hdt
I doubt if we want to change this. This repo can be downloaded by users using all kind of machines. `/usr/local/bin/rdf2hdt` makes the suggestion that the file will always be on that location. On f.e. Windows machines that won't be the case. `/link/to` is more clear that this is a setting that the user will need to change.

Or we could use `atramhasis.rdf2hdt = /usr/local/bin/rdf2hdt` and adjust the comment above, something like `# Location of rdf2hdt executable. Change this location to the path where the rdf2hdt can be found on your machine`

2022-06-23 12:47 UTC, goessebr approved these changes

2022-06-23 12:55 UTC, merged

2022-06-23 19:06 UTC, goessebr commented
Ik zie het nu pas maar er staan nog 2 TODO's in de changes, dient daar nog iets te gebeuren?

2022-06-24 12:31 UTC, roefem commented on atramhasis/scripts/generate_ldf_config.py
> +            "quads": False,  # TODO
@koenedaele @goessebr 
the [migration script](https://github.com/LinkedDataFragments/Server.js/wiki/Release-3.0.0#migration-from-2xx) explicitly set this value to False, so I did so as well here. Should quad patterns be supported? If this field is omitted from the config, it defaults to True