#833 providers json text to numeric
OnroerendErfgoed/atramhasis pull request #835
Opened 2023-05-17 07:45 UTC by vancamti

2023-05-17 10:33 UTC, koenedaele requested changes
We want the old ID's to remain fully functional since they are used in document URL's. Solution is probably somewhere in the code that registers the providers with the registry.

2023-05-17 10:33 UTC, koenedaele commented on atramhasis/scripts/migrate_sqlalchemy_providers.py
> +        meta["id"] = provider.conceptscheme_id
This makes the problem worse as it now fully overwrites the old provider id with the conceptscheme_id. We want the old provider ID to remain functional.

2023-05-17 10:33 UTC, koenedaele commented on tests/scripts/test_migratie_sqlalchemy_providers.py
> +                'id': int(provider.id),
This should actually be 'EXTRA', so the old test was correct.

2023-05-22 07:50 UTC, koenedaele commented
> Do we want both http://localhost:6543/conceptschemes/HERITAGETYPE and http://localhost:6543/conceptschemes/6 to work or should only http://localhost:6543/conceptschemes/HERITAGETYPE work ? Is it required that the provider gets a numerical id `db_provider.id = provider.conceptscheme_id` or can it just be `db_provider.id = db_provider.id = provider.get_vocabulary_id()` ? (which makes the old url fully functional)

The numeric id does not need to be exposed through the URL. So `db_provider.id  = provider.get_vocabulary_id()`

2023-05-22 15:12 UTC, Wim-De-Clercq approved these changes
I do believe that is correct... suspiciously small fix :raised_eyebrow:

2023-05-22 20:45 UTC, koenedaele approved these changes

2023-05-23 07:44 UTC, merged