#856 update 312 requirments
OnroerendErfgoed/atramhasis pull request #867
Opened 2024-06-10 15:23 UTC by vancamti

2024-06-11 08:50 UTC, Wim-De-Clercq approved these changes

2024-06-11 08:50 UTC, Wim-De-Clercq requested changes
.

2024-06-14 07:09 UTC, vancamti commented on atramhasis/views/exception_views.py
> +                list(extract_errors(request, exc.errors))
deze snap ik niet helemaal. op lijn 113 wordt die `_handle_validation_error` nog gebruikt en dat is de enige method die onder deze code staat ?

2024-06-14 07:33 UTC, Wim-De-Clercq commented on atramhasis/views/exception_views.py
> +                list(extract_errors(request, exc.errors))
ja, ik was dom

2024-06-14 07:33 UTC, Wim-De-Clercq approved these changes

2024-06-14 07:45 UTC, merged