Support skosprovider /expand api.
OnroerendErfgoed/atramhasis pull request #904
Opened 2024-07-29 07:30 UTC by Wim-De-Clercq

Issue #903

2024-07-30 11:45 UTC, Wim-De-Clercq commented
Heeft pyramid_skosprovider update nodig.

2024-07-31 10:02 UTC, goessebr requested changes

2024-07-31 10:02 UTC, goessebr commented on atramhasis/routes.py
> +    config.add_route('skosprovider.c.ttl', pattern='/conceptschemes/{scheme_id}/c/{c_id:.*}.ttl')
Is het niet vreemd om hier skosprovider routes te gaan aanmaken? Zou dit dan ook niet beter naar de pyramid_skosprovider gaan?

2024-08-01 09:32 UTC, goessebr approved these changes

2024-08-01 09:38 UTC, merged